import { TranscriptSegment, CallMetadata } from '@/types';

export interface DemoTranscript {
    id: string;
    name: string;
    description: string;
    duration_seconds: number;
    segments: TranscriptSegment[];
    metadata: CallMetadata;
    expected_alerts: string[];
}

export const demoTranscripts: DemoTranscript[] = [
    {
        id: 'dnc-request',
        name: 'DNC Request Scenario',
        description: 'Customer requests to be placed on Do Not Call list. Agent must properly acknowledge and not continue selling.',
        duration_seconds: 45,
        metadata: {
            call_id: 'demo-001',
            agent_id: 'agent-001',
            agent_name: 'Sarah Johnson',
            call_start_time: '2026-01-16T10:30:00Z',
            caller_timezone: 'America/New_York',
            is_dnc_listed: false,
            has_prior_consent: true,
            is_prerecorded: false,
            call_type: 'outbound_sales',
        },
        expected_alerts: ['DNC-001', 'DNC-002'],
        segments: [
            {
                speaker: 'agent',
                text: 'Hi, this is Sarah calling from TeleSolutions with an exciting offer for you today.',
                start_time_ms: 0,
                end_time_ms: 4000,
                start_char: 0,
                end_char: 82,
            },
            {
                speaker: 'customer',
                text: 'Who is this?',
                start_time_ms: 4500,
                end_time_ms: 5500,
                start_char: 83,
                end_char: 95,
            },
            {
                speaker: 'agent',
                text: 'This is Sarah from TeleSolutions. We have a limited time offer on our premium internet package that could save you up to 40% on your monthly bill.',
                start_time_ms: 6000,
                end_time_ms: 13000,
                start_char: 96,
                end_char: 244,
            },
            {
                speaker: 'customer',
                text: 'Look, I\'m not interested. Don\'t call me again, please.',
                start_time_ms: 14000,
                end_time_ms: 17000,
                start_char: 245,
                end_char: 299,
            },
            {
                speaker: 'agent',
                text: 'I understand, but before you go, let me just tell you about our special promotion that ends today.',
                start_time_ms: 18000,
                end_time_ms: 24000,
                start_char: 300,
                end_char: 398,
            },
            {
                speaker: 'customer',
                text: 'I said stop calling me! Put me on your do not call list right now.',
                start_time_ms: 25000,
                end_time_ms: 29000,
                start_char: 399,
                end_char: 465,
            },
            {
                speaker: 'agent',
                text: 'Understood—I\'ll add you to our Do Not Call list effective immediately. You won\'t receive any more marketing calls from us. Have a great day.',
                start_time_ms: 30000,
                end_time_ms: 38000,
                start_char: 466,
                end_char: 606,
            },
        ],
    },
    {
        id: 'dnc-listed-call',
        name: 'DNC Listed Number',
        description: 'Outbound call to a number on the National DNC Registry without prior consent. High severity metadata-based alert.',
        duration_seconds: 30,
        metadata: {
            call_id: 'demo-002',
            agent_id: 'agent-002',
            agent_name: 'Mike Thompson',
            call_start_time: '2026-01-16T11:00:00Z',
            caller_timezone: 'America/Chicago',
            is_dnc_listed: true,
            has_prior_consent: false,
            is_prerecorded: false,
            call_type: 'outbound_sales',
        },
        expected_alerts: ['DNC-003'],
        segments: [
            {
                speaker: 'agent',
                text: 'Good morning! This is Mike from Premium Services calling about an exclusive offer.',
                start_time_ms: 0,
                end_time_ms: 5000,
                start_char: 0,
                end_char: 82,
            },
            {
                speaker: 'customer',
                text: 'Hello? What company is this?',
                start_time_ms: 5500,
                end_time_ms: 7000,
                start_char: 83,
                end_char: 111,
            },
            {
                speaker: 'agent',
                text: 'This is Mike from Premium Services. I\'m calling because you\'ve been selected for our VIP discount program.',
                start_time_ms: 7500,
                end_time_ms: 13000,
                start_char: 112,
                end_char: 218,
            },
            {
                speaker: 'customer',
                text: 'I never signed up for anything. How did you get my number?',
                start_time_ms: 14000,
                end_time_ms: 17000,
                start_char: 219,
                end_char: 277,
            },
        ],
    },
    {
        id: 'consent-revocation',
        name: 'Consent Revocation',
        description: 'Customer revokes consent using non-standard phrasing. Agent must recognize and honor the revocation.',
        duration_seconds: 40,
        metadata: {
            call_id: 'demo-003',
            agent_id: 'agent-003',
            agent_name: 'Jennifer Davis',
            call_start_time: '2026-01-16T14:15:00Z',
            caller_timezone: 'America/Los_Angeles',
            is_dnc_listed: false,
            has_prior_consent: true,
            is_prerecorded: false,
            call_type: 'outbound_sales',
        },
        expected_alerts: ['CONS-001'],
        segments: [
            {
                speaker: 'agent',
                text: 'Hi, this is Jennifer from DataCloud. I\'m calling about your subscription renewal.',
                start_time_ms: 0,
                end_time_ms: 5000,
                start_char: 0,
                end_char: 82,
            },
            {
                speaker: 'customer',
                text: 'Oh, right. What about it?',
                start_time_ms: 5500,
                end_time_ms: 7000,
                start_char: 83,
                end_char: 108,
            },
            {
                speaker: 'agent',
                text: 'We have some great upgrade options that I\'d love to tell you about. Our new premium tier includes unlimited storage.',
                start_time_ms: 7500,
                end_time_ms: 14000,
                start_char: 109,
                end_char: 226,
            },
            {
                speaker: 'customer',
                text: 'Actually, I want to opt out of these marketing calls. I withdraw my consent for you to contact me.',
                start_time_ms: 15000,
                end_time_ms: 21000,
                start_char: 227,
                end_char: 326,
            },
            {
                speaker: 'agent',
                text: 'I understand you\'d like to revoke your consent. I\'ll process that right away and you\'ll be removed from our calling list. Is there anything else I can help with regarding your existing account?',
                start_time_ms: 22000,
                end_time_ms: 32000,
                start_char: 327,
                end_char: 520,
            },
        ],
    },
    {
        id: 'missing-disclosures',
        name: 'Missing Required Disclosures',
        description: 'Agent dives into sales pitch without required TSR disclosures (seller identity, sales purpose, product description).',
        duration_seconds: 35,
        metadata: {
            call_id: 'demo-004',
            agent_id: 'agent-004',
            agent_name: 'Chris Martinez',
            call_start_time: '2026-01-16T09:45:00Z',
            caller_timezone: 'America/Denver',
            is_dnc_listed: false,
            has_prior_consent: true,
            is_prerecorded: false,
            call_type: 'outbound_sales',
        },
        expected_alerts: ['DISC-001', 'DISC-002'],
        segments: [
            {
                speaker: 'agent',
                text: 'Hello! So you\'re definitely going to want to hear about this amazing deal we\'ve got going on.',
                start_time_ms: 0,
                end_time_ms: 5000,
                start_char: 0,
                end_char: 93,
            },
            {
                speaker: 'customer',
                text: 'Wait, who is this?',
                start_time_ms: 5500,
                end_time_ms: 7000,
                start_char: 94,
                end_char: 112,
            },
            {
                speaker: 'agent',
                text: 'Oh, right! I\'m Chris calling from SuperSavers. We\'re reaching out because you qualify for 50% off our annual membership!',
                start_time_ms: 7500,
                end_time_ms: 14000,
                start_char: 113,
                end_char: 233,
            },
            {
                speaker: 'customer',
                text: 'What is this membership for exactly?',
                start_time_ms: 15000,
                end_time_ms: 17000,
                start_char: 234,
                end_char: 270,
            },
            {
                speaker: 'agent',
                text: 'It\'s our premium discount club that gives you access to exclusive deals at over 10,000 retailers. I\'m calling to offer you our special promotional rate.',
                start_time_ms: 17500,
                end_time_ms: 25000,
                start_char: 271,
                end_char: 424,
            },
        ],
    },
    {
        id: 'prerecorded-no-consent',
        name: 'Prerecorded Voice Without Consent',
        description: 'Marketing call using prerecorded voice to a number without prior express written consent.',
        duration_seconds: 25,
        metadata: {
            call_id: 'demo-005',
            agent_id: 'system',
            agent_name: 'Automated System',
            call_start_time: '2026-01-16T10:00:00Z',
            caller_timezone: 'America/New_York',
            is_dnc_listed: false,
            has_prior_consent: false,
            is_prerecorded: true,
            call_type: 'outbound_sales',
        },
        expected_alerts: ['PREC-001'],
        segments: [
            {
                speaker: 'agent',
                text: 'Hello! This is an important message from ValuePlus about a special limited-time offer available exclusively to you.',
                start_time_ms: 0,
                end_time_ms: 6000,
                start_char: 0,
                end_char: 114,
            },
            {
                speaker: 'agent',
                text: 'Press 1 now to speak with a representative and claim your free gift valued at over $200.',
                start_time_ms: 6500,
                end_time_ms: 12000,
                start_char: 115,
                end_char: 202,
            },
            {
                speaker: 'agent',
                text: 'This offer expires at midnight tonight, so don\'t delay! Press 1 now or call us back at 1-800-555-0123.',
                start_time_ms: 13000,
                end_time_ms: 20000,
                start_char: 203,
                end_char: 305,
            },
        ],
    },
];
