import { StoredAlert, AnalyticsData } from '@/types';

// Mock stored alerts for admin view
export const mockAlerts: StoredAlert[] = [
    {
        id: 'alert-001',
        call_id: 'call-2026-01-15-001',
        agent_id: 'agent-001',
        agent_name: 'Sarah Johnson',
        rule_id: 'DNC-001',
        title: 'Customer Requested No Further Calls',
        severity: 'high',
        confidence: 92,
        evidence: {
            quote: 'Don\'t call me again, please.',
            start_char: 245,
            end_char: 273,
        },
        why_it_matters: 'Under TCPA, consumers can revoke consent by any reasonable means at any time.',
        agent_fix_suggestion: 'Understood—I\'ll add you to our Do Not Call list effective immediately.',
        created_at: '2026-01-15T14:32:00Z',
    },
    {
        id: 'alert-002',
        call_id: 'call-2026-01-15-001',
        agent_id: 'agent-001',
        agent_name: 'Sarah Johnson',
        rule_id: 'DNC-002',
        title: 'Agent Continued After DNC Request',
        severity: 'high',
        confidence: 88,
        evidence: {
            quote: 'but before you go, let me just tell you',
            start_char: 300,
            end_char: 340,
        },
        why_it_matters: 'After a DNC request, any attempt to continue selling significantly increases violation risk.',
        agent_fix_suggestion: 'Do not continue selling. Acknowledge the request and end the call professionally.',
        created_at: '2026-01-15T14:33:00Z',
    },
    {
        id: 'alert-003',
        call_id: 'call-2026-01-15-002',
        agent_id: 'agent-002',
        agent_name: 'Mike Thompson',
        rule_id: 'DNC-003',
        title: 'National DNC List - No Consent Evidence',
        severity: 'high',
        confidence: 95,
        evidence: {
            quote: 'Number flagged as DNC-listed in system metadata',
            start_char: 0,
            end_char: 0,
        },
        why_it_matters: 'Calling numbers on the National DNC Registry without prior express consent is a TCPA violation.',
        agent_fix_suggestion: 'Verify consent documentation before proceeding with marketing calls to DNC-listed numbers.',
        created_at: '2026-01-15T11:15:00Z',
    },
    {
        id: 'alert-004',
        call_id: 'call-2026-01-14-003',
        agent_id: 'agent-003',
        agent_name: 'Jennifer Davis',
        rule_id: 'CONS-001',
        title: 'Consent Revocation Detected',
        severity: 'high',
        confidence: 85,
        evidence: {
            quote: 'I want to opt out of these marketing calls',
            start_char: 227,
            end_char: 269,
        },
        why_it_matters: 'Under TCPA, consumers can revoke consent by any reasonable means.',
        agent_fix_suggestion: 'I understand you\'d like to revoke your consent. I\'ll process that right away.',
        created_at: '2026-01-14T16:45:00Z',
    },
    {
        id: 'alert-005',
        call_id: 'call-2026-01-14-004',
        agent_id: 'agent-004',
        agent_name: 'Chris Martinez',
        rule_id: 'DISC-001',
        title: 'Missing Seller Identity Disclosure',
        severity: 'medium',
        confidence: 75,
        evidence: {
            quote: 'So you\'re definitely going to want to hear about this amazing deal',
            start_char: 0,
            end_char: 60,
        },
        why_it_matters: 'FTC TSR requires prompt disclosure of the seller\'s identity.',
        agent_fix_suggestion: 'Hi, my name is [Name] calling from [Company Name].',
        created_at: '2026-01-14T09:50:00Z',
    },
    {
        id: 'alert-006',
        call_id: 'call-2026-01-13-005',
        agent_id: 'agent-001',
        agent_name: 'Sarah Johnson',
        rule_id: 'DNC-001',
        title: 'Customer Requested No Further Calls',
        severity: 'high',
        confidence: 90,
        evidence: {
            quote: 'Remove me from your list',
            start_char: 180,
            end_char: 205,
        },
        why_it_matters: 'Under TCPA, consumers can revoke consent by any reasonable means at any time.',
        agent_fix_suggestion: 'Understood—I\'ll add you to our Do Not Call list effective immediately.',
        created_at: '2026-01-13T10:20:00Z',
    },
    {
        id: 'alert-007',
        call_id: 'call-2026-01-13-006',
        agent_id: 'agent-002',
        agent_name: 'Mike Thompson',
        rule_id: 'DISC-002',
        title: 'Missing Sales Call Nature Disclosure',
        severity: 'medium',
        confidence: 70,
        evidence: {
            quote: 'I wanted to talk to you about something important',
            start_char: 50,
            end_char: 100,
        },
        why_it_matters: 'The TSR requires disclosure that the call is for sales purposes.',
        agent_fix_suggestion: 'I\'m calling today with a special offer for you...',
        created_at: '2026-01-13T15:30:00Z',
    },
    {
        id: 'alert-008',
        call_id: 'call-2026-01-12-007',
        agent_id: 'agent-005',
        agent_name: 'Automated System',
        rule_id: 'PREC-001',
        title: 'Prerecorded Voice Without Consent',
        severity: 'high',
        confidence: 95,
        evidence: {
            quote: 'Call flagged as using prerecorded voice without consent',
            start_char: 0,
            end_char: 0,
        },
        why_it_matters: 'TCPA requires prior express written consent for prerecorded telemarketing calls.',
        agent_fix_suggestion: 'Ensure written consent is obtained before using prerecorded messages.',
        created_at: '2026-01-12T08:00:00Z',
    },
    {
        id: 'alert-009',
        call_id: 'call-2026-01-12-008',
        agent_id: 'agent-003',
        agent_name: 'Jennifer Davis',
        rule_id: 'IDENT-001',
        title: 'Missing Callback Number',
        severity: 'low',
        confidence: 65,
        evidence: {
            quote: 'Thanks for your time, goodbye',
            start_char: 500,
            end_char: 530,
        },
        why_it_matters: 'Telemarketers must provide a means for consumers to reach the business.',
        agent_fix_suggestion: 'If you have any questions, you can reach us at [phone number].',
        created_at: '2026-01-12T14:15:00Z',
    },
    {
        id: 'alert-010',
        call_id: 'call-2026-01-11-009',
        agent_id: 'agent-004',
        agent_name: 'Chris Martinez',
        rule_id: 'CONS-001',
        title: 'Consent Revocation Detected',
        severity: 'high',
        confidence: 82,
        evidence: {
            quote: 'I never agreed to receive these calls',
            start_char: 150,
            end_char: 188,
        },
        why_it_matters: 'Under TCPA, consumers can revoke consent by any reasonable means.',
        agent_fix_suggestion: 'I understand. I\'ll make sure you\'re removed from our calling list immediately.',
        created_at: '2026-01-11T11:45:00Z',
    },
];

// Mock analytics data
export const mockAnalytics: AnalyticsData = {
    total_calls: 847,
    total_alerts: 156,
    alerts_by_severity: {
        high: 68,
        medium: 52,
        low: 36,
    },
    alerts_by_rule: [
        { rule_id: 'DNC-001', count: 42 },
        { rule_id: 'CONS-001', count: 28 },
        { rule_id: 'DNC-003', count: 24 },
        { rule_id: 'DISC-001', count: 22 },
        { rule_id: 'DNC-002', count: 15 },
        { rule_id: 'DISC-002', count: 12 },
        { rule_id: 'PREC-001', count: 8 },
        { rule_id: 'IDENT-001', count: 5 },
    ],
    alerts_by_agent: [
        { agent_id: 'agent-001', agent_name: 'Sarah Johnson', count: 35 },
        { agent_id: 'agent-002', agent_name: 'Mike Thompson', count: 42 },
        { agent_id: 'agent-003', agent_name: 'Jennifer Davis', count: 28 },
        { agent_id: 'agent-004', agent_name: 'Chris Martinez', count: 38 },
        { agent_id: 'agent-005', agent_name: 'Automated System', count: 13 },
    ],
    daily_trend: [
        { date: '2026-01-10', count: 18 },
        { date: '2026-01-11', count: 22 },
        { date: '2026-01-12', count: 25 },
        { date: '2026-01-13', count: 19 },
        { date: '2026-01-14', count: 28 },
        { date: '2026-01-15', count: 32 },
        { date: '2026-01-16', count: 12 },
    ],
};
